server:
  port: 8085
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/resttest
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/resttest
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: 40nqMd7zuZ8avuwGLmh4PbfnmYCM8D9t
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: 40nqMd7zuZ8avuwGLmh4PbfnmYCM8D9t
          discovery:
            provider: keycloak
            client-id: admin-service
            client-secret: 40nqMd7zuZ8avuwGLmh4PbfnmYCM8D9t
            authorization-grant-type: client_credentials
            scope:
              - discovery
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka