scrape_configs:
  - job_name: resttest_admin_service
    static_configs:
      - targets: ["http://172.17.0.1:8085"]
        labels:
          application: resttest_admin_service
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: a4lepuJGoUrQKzNqtTZe7TuxEr6FPPF5
      token_url: http://172.17.0.1:8082/realms/resttest/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials