resttest:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: postgres
    password: root
  security:
    oauth2:
      client:
        provider:
         keycloak:
           issuer-uri: http://localhost:8082/realms/resttest
           user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: S62KQWrnKLdDNZZF7eawo7uPYRiaa66m
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt