resttest:
  services:
    catalogue:
      uri: lb://resttest-catalogue-service
      registration-id: keycloak
spring:
  application:
    name: resttest-manager-app
  boot:
    admin:
      client:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: postgres
    password: root
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/resttest
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: S62KQWrnKLdDNZZF7eawo7uPYRiaa66m
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: manager-app
            client-secret: S62KQWrnKLdDNZZF7eawo7uPYRiaa66m
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: manager-app
            client-secret: S62KQWrnKLdDNZZF7eawo7uPYRiaa66m
            authorization-grant-type: client_credentials
            scope:
              - discovery
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/resttest
management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true